### ISSUE TITLE
Homework Submit

### ISSUE THREAD

**Issue by Sweetlemon68** [ayf19/sast2022-react-training#1]
Git repository: [SAST2022-React-training](https://git.tsinghua.edu.cn/mrj21/sast2022-react-training)

Frontend deploying address (nginx): http://sast.sweetlemon.top:45716/, https://sast.sweetlemon.top:45716/.

I have also tried to implement a naive frontend written with Semantic UI (without React) deploying at https://sast-2022-frontend-naive.vercel.app/, whose git repository is at [naive frontend](https://git.tsinghua.edu.cn/mrj21/sast2022-frontend-jquery).

**Comment by A1phaN** [comment]
React 的这一份实现的很好，在实现上可以说达到了比较好的水平，不过需要注意一些工程上的问题：
- 需要注意代码格式化，比较明显的几处问题有：
  - 多行 TSX 应该用小括号包括起来；
  - 箭头函数写多于一个语句时应该换行；
  - `if` 后面跟一个很多行的语句时，即使只有一个语句最好也加括号；

  当然代码风格问题见仁见智，上面几点仅供参考，可以算是比较常见的一些习惯。
- 注意异常处理，看到有几处用了 `.catch(_ => {})`，但是比如说查看历史记录时 API 报错，应该给用户一个提示，而不是什么都不做。

jQuery 的那一部分我不够熟悉，不在工程上做出评判。

**Comment by yhx-12243** [comment]
卷卷猫猫来啦！说到 Semantic UI 的话，要和 React 配合最好使用 [`semantic-ui-react`](https://react.semantic-ui.com/) 这个包（专门对 `react` 玩家使用 Semantic UI 的组件库），可以避免 `jQuery` 的暴力前端操作，具体可以看[我的实现](5)喵~

**Comment by Sweetlemon68** [comment]
> 卷卷猫猫来啦！说到 Semantic UI 的话，要和 React 配合最好使用 [`semantic-ui-react`](https://react.semantic-ui.com/) 这个包（专门对 `react` 玩家使用 Semantic UI 的组件库），可以避免 `jQuery` 的暴力前端操作，具体可以看[我的实现](5)喵~

谢谢啦（

那个暴力版是当时没学 React 写着玩的，算是实践一下 JS（bushi
