### ISSUE TITLE
Homework Submit 

### ISSUE THREAD

**Issue by YfLi03** [ayf19/sast2022-react-training#2]
repo: https://github.com/YfLi03/SASTSummer_react
deployed at: http://sast.iceeera.com:45758 (with my own backend)
上传头像有可能有问题 ()

**Comment by A1phaN** [comment]
实现的不错，也用了不少复杂的组件，不过需要注意一点代码风格，比如说导入模块的时候加引号、使用 `let` 而不是 `var`、返回无需显示的组件时使用 `null` 而不是 `<></>` 等，可以尝试使用一些代码格式化工具，或者去读一些项目的源代码。

需要注意的问题是，React 函数组件会在每次重新渲染时都执行一次，如果某些东西没有太大必要的话可以不要写在函数体内，比如说 `src/component/ModalHistory.tsx` 中的 `getDate` 函数，写在组件外可以减少调用开销。

**Comment by YfLi03** [comment]
> 实现的不错，也用了不少复杂的组件，不过需要注意一点代码风格，比如说导入模块的时候加引号、使用 `let` 而不是 `var`、返回无需显示的组件时使用 `null` 而不是 `<></>` 等，可以尝试使用一些代码格式化工具，或者去读一些项目的源代码。
> 
> 需要注意的问题是，React 函数组件会在每次重新渲染时都执行一次，如果某些东西没有太大必要的话可以不要写在函数体内，比如说 `src/component/ModalHistory.tsx` 中的 `getDate` 函数，写在组件外可以减少调用开销。

收到，感谢！
