### ISSUE TITLE
homework submit

### ISSUE THREAD

**Issue by Xial-kotori** [ayf19/sast2022-react-training#4]
repository: [undefined](https://git.tsinghua.edu.cn/yuancf21/summer2022-hw6-react)

deploy: [59.66.131.240:45213](http://59.66.131.240:45213)

很多实现各种意义上都很鬼畜

**Comment by A1phaN** [comment]
功能实现的基本都不错，一个 bug 是背景图会跟着页面滚动，这里需要给 body::before 添加 position: fixed 的属性。

另外需要注意的点是错误提示，比如展开历史记录时请求失败应该给用户可以看到的提示（而不是只有 console.error，在正式版本中不应该出现此类供调试的输出），比如使用气泡等。

仅用于组件内的变量应当使用 state 而不是全局变量，大段的静态数据应当单独放在一些地方，而不是夹在代码中间（src/LeaderBoard.tsx）。

代码风格上需要多留意，有一些地方没有添加分号，还有一些缩进之类的问题，可以尝试使用格式化工具。
