### ISSUE TITLE
涵猫前端~

### ISSUE THREAD

**Issue by yhx-12243** [ayf19/sast2022-react-training#5]
https://git.tsinghua.edu.cn/yu-hx21/sast2022-react-training

前端地址：http://59.66.131.240:45731/

~~新鲜的 `semantic-ui-react` 实现！（雾~~

目前已实现基本功能，高级功能如切换后端地址（目前后端锁定在 http://59.66.131.240:45733/ ）以及个人服务器部署先鸽着，仓库会实时更新~ 😊

**Comment by yhx-12243** [comment]
个人服务器前端部署已完成😋

链接：https://43.138.56.99/sast2022/leaderboard （注意是 HTTPS 哦，所以只支持访问 HTTPS 的后端）

默认后端更换为 https://s.back.sast2022.lmd.red 。

切换后端 UI 懒得写了，直接去 “偏好设置” 中**添加**如下配置：

```json
{
	"sast2022": {
		"leaderBoard": {
			"backendUrl": "<你想访问的 HTTPS 后端地址>"
		}
	}
}
```

重进页面即可~

HTTPS 的后端地址除了默认后端外还有 https://sast.sweetlemon.top:45719 等，均可尝试！

**Comment by A1phaN** [comment]
🐠大写的说实话不完全懂，因为没用过 semantic-ui，总体来说工程上做的很好吧，提一点建议是当需要很复杂的反向数据流（指那个 Context 传函数）的时候可以尝试用 Redux 管理全局状态，或者尝试使用 swr 这种工具来管理数据请求。

**Comment by A1phaN** [comment]
哦对了这个脚本应当是有问题的，直接 yarn && yarn build 是会报错的
