### ISSUE TITLE
Homework Submission

### ISSUE THREAD

**Issue by abmfy** [ayf19/sast2022-react-training#6]
代码仓库：https://git.tsinghua.edu.cn/wangbw21/sast2022-react-training
部署地址：http://59.66.131.240:45441

**Comment by A1phaN** [comment]
功能实现不错，有学号合法性验证好评。

一些问题：
- 加载数据前整个页面的高度很小，导致下面有大段空白，可以尝试 min-height 属性
- 逻辑上讲上传数据的表单在上传之后应当重置，或者至少应当清除 result.txt 的值
- 查看历史信息的时候如果请求错误应当有提示，而不是展示空白数据
- 不要在 useState 里添加副作用（src/LeaderBoard.tsx），这种需求可以使用一个 useState 和一个 useEffect
- 适当注意代码格式化的问题
