### ISSUE TITLE
homework  submit (Finished)

### ISSUE THREAD

**Issue by Lethe10137** [ayf19/sast2022-react-training#7]
I am trying to finish the homework before ddl, but it seems that I fail.
Some problems exists in current version, and I will try to fix them.
https://git.tsinghua.edu.cn/ch-li21/react_homework
2021010826

**Comment by ayf19** [comment]
功能上基本实现不错，但是有个bug是背景图片会被滚动走，这里需要给 body::before 上添加 position: fixed 的属性。

另外可以注意的是如果请求发生错误，可以给用户适当的提示，而且比如说展开历史记录时没有获取到信息，可以给气泡提示等（而不是 console.error），这里可以想办法自动把展开按钮变为未展开状态，不过大概看了下可能不是太简单。

最后就是注意代码格式化，很多地方并没有添加分号，也有些其他的缩进不适当等等，可以尝试使用格式化工具。

**Comment by A1phaN** [comment]
刚刚回复错 issue，稍后 review 这个

**Comment by Lethe10137** [comment]
finished 
https://git.tsinghua.edu.cn/ch-li21/react_homework/
http://59.66.131.240:45546

**Comment by A1phaN** [comment]
review 鸽的时间略长了一点，抱歉。功能上是没问题的，不过工程上还有比较多值得优化的地方，可以参考以下一些点，也可以去看看其他同学的实现

样式上来说，页面最大宽度可以限制下，SubmitForm 作为 Footer 是否合适可能需要斟酌下，尤其是 SubmitForm 的宽度可以调整下，要考虑到浏览器开很宽的时候的表现

代码上注意代码本身格式化，还有注意一些代码风格，比如说不要用太多的 any，不要无缘无故打很多空行，不要在一个组件内局部的 function 和箭头函数混用等等

此外功能上的一个小漏洞是提交表单之后应当清除表单数据以便下次填写
